### ISSUE TITLE
Grammar improvements for German

### ISSUE THREAD

**Issue by t-book** [xfra35/f3-multilang-demo#2]
Hi xfra35,

 I´d like to help a bit with german translations. Can you tell me what is meant here:

**If a page is not found, the language is set at best:**
http://ml.aesx.fr/en/missing

"set at best" is it a fallback to the default language?

Further 

**Here's an example for this page:**
http://ml.aesx.fr/en/seo

In my opinion this is a bit hard to understand I thought that this is the upper menu but could not see the hreflang attibute. Maybe it would be clearer to give some more information about how this is working?

great work and thanks for the plugin,

– anatol

**Comment by xfra35** [comment]
Hi Anatol, thanks for helping =)

When a page is not found, the language is guessed, when possible. So for example, when requesting a non-existing URL called `/en/foo-bar`, the plugin assumes that the expected language is English. But when requesting a non-existing URL called `/foo-bar` or `/zz/foo-bar`, no language can be guessed and therefore we fallback to the browser preferred language.

> In my opinion this is a bit hard to understand

Are you talking about the hreflangs? You need to view the HTML source page to understand what's the expected result.

**Comment by t-book** [comment]
ok, great got it :) I´ve created another pull request addressing these cases.
